blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ Ask a question
    url: https://github.com/orgs/ihub-pub/discussions/categories/q-a
    about: æå‡ºé—®é¢˜å¹¶ä¸å…¶ä»–ç¤¾åŒºæˆå‘˜è®¨è®º
  - name: ğŸ“š Document
    url: https://doc.ihub.pub
    about: å¸®åŠ©æ–‡æ¡£
